In [167]:
!pip install glob

ERROR: Could not find a version that satisfies the requirement glob (from versions: none)
ERROR: No matching distribution found for glob

In [168]:
import glob

In [169]:
df1 = pd.read_csv('data1.csv')
df2 = pd.read_csv('data2.csv')
df3 = pd.read_csv('data3.csv')
df4 = pd.read_csv('data4.csv')
df5 = pd.read_csv('data5.csv')
df6 = pd.read_csv('data6.csv')
df6 = pd.read_csv('data7.csv')
df8 = pd.read_csv('data9.csv')
df9 = pd.read_csv('data9.csv')
df10 = pd.read_csv('data10.csv')
df11 = pd.read_csv('data11.csv')

In [170]:
import pandas as pd

# List your DataFrames
dfs = [df1, df2, df3, df4, df5, df6, df8, df10, df11]

# Concatenate into one DataFrame
merged_df = pd.concat(dfs, ignore_index=True)

# Save to a single CSV file
merged_df.to_csv('merged_output.csv', index=False)

In [171]:
merged_df

                 bus_name  amount                          about  rating
0             KMS Travels    ₹810              A/C Sleeper (2+1)     3.8
1             KMS Travels    ₹580  Bharat Benz A/C Sleeper (2+1)     4.8
2              A1 Travels    ₹555  Bharat Benz A/C Sleeper (2+1)     4.5
3        No 1 Air Travels    ₹600  Bharat Benz A/C Sleeper (2+1)     4.3
4    Jihan luxury travels    ₹600              A/C Sleeper (2+1)     3.7
..                    ...     ...                            ...     ...
164         Svkdt travels  ₹1,900              A/C Sleeper (2+1)     4.1
165      Sri Auto Travels    ₹879              A/C Sleeper (2+1)     2.8
166      Sri Auto Travels    ₹999              A/C Sleeper (2+1)     2.8
167  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.5
168  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.3

[169 rows x 4 columns]

In [172]:
df = merged_df

In [173]:
df

                 bus_name  amount                          about  rating
0             KMS Travels    ₹810              A/C Sleeper (2+1)     3.8
1             KMS Travels    ₹580  Bharat Benz A/C Sleeper (2+1)     4.8
2              A1 Travels    ₹555  Bharat Benz A/C Sleeper (2+1)     4.5
3        No 1 Air Travels    ₹600  Bharat Benz A/C Sleeper (2+1)     4.3
4    Jihan luxury travels    ₹600              A/C Sleeper (2+1)     3.7
..                    ...     ...                            ...     ...
164         Svkdt travels  ₹1,900              A/C Sleeper (2+1)     4.1
165      Sri Auto Travels    ₹879              A/C Sleeper (2+1)     2.8
166      Sri Auto Travels    ₹999              A/C Sleeper (2+1)     2.8
167  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.5
168  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.3

[169 rows x 4 columns]

In [174]:
# we will do some preprocessing

df

                 bus_name  amount                          about  rating
0             KMS Travels    ₹810              A/C Sleeper (2+1)     3.8
1             KMS Travels    ₹580  Bharat Benz A/C Sleeper (2+1)     4.8
2              A1 Travels    ₹555  Bharat Benz A/C Sleeper (2+1)     4.5
3        No 1 Air Travels    ₹600  Bharat Benz A/C Sleeper (2+1)     4.3
4    Jihan luxury travels    ₹600              A/C Sleeper (2+1)     3.7
..                    ...     ...                            ...     ...
164         Svkdt travels  ₹1,900              A/C Sleeper (2+1)     4.1
165      Sri Auto Travels    ₹879              A/C Sleeper (2+1)     2.8
166      Sri Auto Travels    ₹999              A/C Sleeper (2+1)     2.8
167  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.5
168  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.3

[169 rows x 4 columns]

In [177]:
df

                 bus_name  amount                          about  rating
0             KMS Travels    ₹810              A/C Sleeper (2+1)     3.8
1             KMS Travels    ₹580  Bharat Benz A/C Sleeper (2+1)     4.8
2              A1 Travels    ₹555  Bharat Benz A/C Sleeper (2+1)     4.5
3        No 1 Air Travels    ₹600  Bharat Benz A/C Sleeper (2+1)     4.3
4    Jihan luxury travels    ₹600              A/C Sleeper (2+1)     3.7
..                    ...     ...                            ...     ...
164         Svkdt travels  ₹1,900              A/C Sleeper (2+1)     4.1
165      Sri Auto Travels    ₹879              A/C Sleeper (2+1)     2.8
166      Sri Auto Travels    ₹999              A/C Sleeper (2+1)     2.8
167  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.5
168  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.3

[169 rows x 4 columns]

In [180]:
df.columns

Index(['bus_name', 'amount', 'about', 'rating'], dtype='object')

In [181]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\prem kumar\appdata\local\programs\python\python312\lib\site-packages (1.1.1)Note: you may need to restart the kernel to use updated packages.

In [188]:
engine = create_engine(
    "mysql+pymysql://7Z3SRE1xmB2xsHv.root:Rloj46Ewjuq6O8SY@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/PROJECT_2"
)

In [204]:
data = pd.read_csv("df.csv")
data

                 bus_name  amount                          about  rating
0             KMS Travels    ₹810              A/C Sleeper (2+1)     3.8
1             KMS Travels    ₹580  Bharat Benz A/C Sleeper (2+1)     4.8
2              A1 Travels    ₹555  Bharat Benz A/C Sleeper (2+1)     4.5
3        No 1 Air Travels    ₹600  Bharat Benz A/C Sleeper (2+1)     4.3
4    Jihan luxury travels    ₹600              A/C Sleeper (2+1)     3.7
..                    ...     ...                            ...     ...
164         Svkdt travels  ₹1,900              A/C Sleeper (2+1)     4.1
165      Sri Auto Travels    ₹879              A/C Sleeper (2+1)     2.8
166      Sri Auto Travels    ₹999              A/C Sleeper (2+1)     2.8
167  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.5
168  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.3

[169 rows x 4 columns]

In [200]:
import pandas as pd
from sqlalchemy import create_engine

# Step 1: Load your dataset into a pandas DataFrame
data = pd.read_csv("df.csv")  # Replace with your CSV path

# Step 2: Create a secure SQLAlchemy connection to TiDB (with SSL enabled)
engine = create_engine(
    "mysql+pymysql://7Z3SRE1xmB2xsHv.root:Rloj46Ewjuq6O8SY@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/PROJECT_2?ssl_ca=true"
)

In [232]:
import pandas as pd
from sqlalchemy import create_engine

# ✅ Establish connection with TiDB
engine = create_engine(
    "mysql+pymysql://7Z3SRE1xmB2xsHv.root:Rloj46Ewjuq6O8SY@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/PROJECT_2?ssl_ca=true"
)

# ✅ Correct CSV path
data = pd.read_csv("df.csv")

# ✅ Upload to TiDB
data.to_sql('bus_data1', engine, if_exists='replace', index=False)

print("✅ Data uploaded successfully!")

FileNotFoundError: [Errno 2] No such file or directory

In [233]:
import os
print(os.listdir())  # Shows files/folders in the current working directory

['Anaconda Navigator.lnk', 'data.1.ipynb', 'data1.csv', 'data10.csv', 'data10.ipynb', 'data11.csv', 'data2.csv', 'data2.ipynb', 'data3.csv', 'data3.ipynb', 'data4.csv', 'data4.ipynb', 'data5.csv', 'data5.ipynb', 'data6.csv', 'data6.ipynb', 'data7.csv', 'data7.ipynb', 'data8', 'data8.ipynb', 'data9.csv', 'data9.ipynb', 'df', 'df.csv', 'main.ipynb', 'merged_output.csv', 'seleninum.ipynb']

In [236]:
import pandas as pd
from sqlalchemy import create_engine

# ✅ Connect to TiDB
engine = create_engine(
    "mysql+pymysql://7Z3SRE1xmB2xsHv.root:Rloj46Ewjuq6O8SY@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/PROJECT_2?ssl_ca=true"
)

# ✅ Corrected CSV path
data = pd.read_csv("df/df.csv")

# ✅ Upload to SQL
data.to_sql('bus_data1', engine, if_exists='replace', index=False)

print("✅ Data uploaded successfully!")

FileNotFoundError: [Errno 2] No such file or directory: 'df/df.csv'

In [228]:
# import necessary packages
import pandas
import psycopg2
from sqlalchemy import create_engine

# establish connection with the database
engine = create_engine(
    "mysql+pymysql://7Z3SRE1xmB2xsHv.root:Rloj46Ewjuq6O8SY@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/PROJECT_2?ssl_ca=true"
)

# read the pandas dataframe
data = pandas.read_csv("df.csv")

# connect the pandas dataframe with postgresql table
data.to_sql('bus_data1', engine, if_exists='replace')

FileNotFoundError: [Errno 2] No such file or directory

In [220]:
data = pd.read_csv("df.csv")

In [221]:
import os
print(os.path.exists("C:/Users/Prem Kumar/Desktop/bus_data.csv"))

False

In [195]:
pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.10-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Downloading psycopg2-2.9.10-cp312-cp312-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   --------------------------- ------------ 0.8/1.2 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 5.2 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.10
Note: you may need to restart the kernel to use updated packages.

In [175]:
# HOST:

# gateway01.ap-southeast-1.prod.aws.tidbcloud.com

# PORT:

# 4000

# USERNAME:

# 7Z3SRE1xmB2xsHv.root

# PASSWORD:

# Rloj46Ewjuq6O8SY

# DATABASE:

# PROJECT_2

In [176]:
df

                 bus_name  amount                          about  rating
0             KMS Travels    ₹810              A/C Sleeper (2+1)     3.8
1             KMS Travels    ₹580  Bharat Benz A/C Sleeper (2+1)     4.8
2              A1 Travels    ₹555  Bharat Benz A/C Sleeper (2+1)     4.5
3        No 1 Air Travels    ₹600  Bharat Benz A/C Sleeper (2+1)     4.3
4    Jihan luxury travels    ₹600              A/C Sleeper (2+1)     3.7
..                    ...     ...                            ...     ...
164         Svkdt travels  ₹1,900              A/C Sleeper (2+1)     4.1
165      Sri Auto Travels    ₹879              A/C Sleeper (2+1)     2.8
166      Sri Auto Travels    ₹999              A/C Sleeper (2+1)     2.8
167  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.5
168  Rathimeena Travels C    ₹534              A/C Sleeper (2+1)     4.3

[169 rows x 4 columns]